image: gradle:8.11.1-jdk17-alpine

variables:
  GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle
  JIB_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

stages:
  - build
  - deploy

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .gradle/wrapper/
    - .gradle/caches/

build:
  stage: build
  script:
    - ./gradlew clean jib
  only:
    - main
    - dev
  interruptible: true

deploy:
  stage: deploy
  needs:
    - job: build
  variables:
    DOCKER_LATEST_IMAGE_NAME: $CI_REGISTRY_IMAGE:latest
  before_script:
    - docker login $CI_REGISTRY -u $TOKEN_USER --password $TOKEN_PWD
  script:
    - docker pull $DOCKER_LATEST_IMAGE_NAME
    - docker stop $CI_PROJECT_NAME;echo $?
    - docker rm -f $CI_PROJECT_NAME;echo $?
    - docker run -d -p 50050:50050 -e JASYPT_ENCRYPTOR_PASSWORD=$CLOUD_ENC_PWD --restart=unless-stopped --name $CI_PROJECT_NAME $DOCKER_LATEST_IMAGE_NAME
    - docker system prune -f
  after_script:
    - docker logout
  tags:
    - winos
  only:
    - main
    - dev
  interruptible: true