default:
  before_script:
    - echo "$TOKEN_PWD" | docker login $CI_REGISTRY -u $TOKEN_USER --password-stdin
  after_script:
    - docker logout

stages:
  - build
  - deploy

build:
  stage: build
  image: docker:20.10.16
  variables:
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  services:
    - docker:20.10.16-dind
  script:
    - docker build --pull -t $DOCKER_IMAGE_NAME .
    - docker push $DOCKER_IMAGE_NAME
    - docker tag $DOCKER_IMAGE_NAME $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - main

deploy:
  stage: deploy
  needs:
    - job: build
  variables:
    DOCKER_LATEST_IMAGE_NAME: $CI_REGISTRY_IMAGE:latest
    DOCKER_TAG_NAME: $CI_PROJECT_NAME:latest
  script:
    - docker rmi $DOCKER_LATEST_IMAGE_NAME;echo $?
    - docker pull $DOCKER_LATEST_IMAGE_NAME
    - docker tag $DOCKER_LATEST_IMAGE_NAME $DOCKER_TAG_NAME
    - docker run -d -p 50050:50050 --rm -e CLOUD_ENC_PWD=$CLOUD_ENC_PWD --restart always --name $CI_PROJECT_NAME $DOCKER_TAG_NAME
  tags:
    - winos
  only:
    - main